# -*- coding: utf-8 -*-
"""C.I.E=1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnOJfUrqMfcJaIyH3xw8teI-oftnDXZF
"""

import pandas as pd
data=pd.read_csv("/content/dataset cars.csv")
print(data)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/dataset cars.csv")
sns.histplot(data['mpg'],bins=10,color='blue',alpha=0.7)
plt.xlabel('mpg')
plt.ylabel('frequency')
plt.title('histogram')
plt.grid(True)
plt.show()



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/dataset cars.csv")
sns.barplot(x='wt',y='mpg',data=data)
plt.xlabel('wt')
plt.ylabel('mpg')
plt.title('bar')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/dataset cars.csv")
sns.scatterplot(x='wt',y='mpg',data=data)
plt.xlabel('wt')
plt.ylabel('mpg')
plt.title('scatter')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/dataset cars.csv")
sns.boxplot(x='wt',y='mpg',data=data)
plt.xlabel('mpg')
plt.ylabel('wt')
plt.title('box')
plt.grid(True)
plt.show()